//
//  Question.swift
//  QuizApp
//
//  Created by jaemin park on 2022/01/23.
//

import Foundation

struct Question: Hashable {
    let questionText: String
    let possibleAnswers: [String]
    let correctAnswerIndex: Int
    
static let allQuestions: [Question] = [
    Question(questionText: "다음 한자를 히라가나로 어떻게 읽는가?\n人脈",
             possibleAnswers: [
             "じんみゃく",
             "じんまく",
             "にんみゃく",
             "にんまく",
             ],
            correctAnswerIndex: 0),
    Question(questionText: "다음 한자를 히라가나로 어떻게 읽는가?\n賢い",
             possibleAnswers: [
             "するどい",
             "かしこい",
             "すごい",
             "えらい",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "다음 한자를 히라가나로 어떻게 읽는가?\n顕著",
             possibleAnswers: [
             "げんちょ",
             "けんしょ",
             "けんちょ",
             "げんしょ",
             ],
             correctAnswerIndex: 2),
    Question(questionText: "다음 한자를 히라가나로 어떻게 읽는가?\n多岐",
             possibleAnswers: [
             "たき",
             "たじ",
             "たぎ",
             "たし",
             ],
             correctAnswerIndex: 0),
    Question(questionText: "다음 한자를 히라가나로 어떻게 읽는가?\n廃れて",
             possibleAnswers: [
             "くずれて",
             "かすれて",
             "つぶれて",
             "すたれて",
             ],
             correctAnswerIndex: 3),
    Question(questionText: "다음 한자를 히라가나로 어떻게 읽는가?\n相場",
             possibleAnswers: [
             "あいば",
             "そうば",
             "あいじょう",
             "そうじょう",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 올바른 단어를 선택하세요.\n私はこの土地で定職に就き、生活の(❓)を築いた。",
             possibleAnswers: [
             "根拠",
             "基盤",
             "根源",
             "基地",
             ],
             correctAnswerIndex: 1),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 올바른 단어를 선택하세요.\n議論は難航すると思ったが、すぐに意見がまとまり、(❓)結論が出た。",
    possibleAnswers: [
"すんなり",
"うっとり",
"ふんわり",
"こっそり",
    ],
    correctAnswerIndex: 0),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 올바른 단어를 선택하세요.\nさっき駅前で佐藤さんを(❓)んですが、今、海外にいるはずなのに変ですね。",
    possibleAnswers: [
"見合わせた",
"見過ごした",
"見かけた",
"見違えた",
    ],
    correctAnswerIndex: 2),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 올바른 단어를 선택하세요.\n市長の責任ある行動が住民の不安を(❓)し、行政に対する期待が一気に高まった。",
    possibleAnswers: [
"一掃",
"追放",
"削除",
"排出",
    ],
    correctAnswerIndex: 0),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 올바른 단어를 선택하세요.\n十分に煮た野菜は味が(❓)柔らかく、とてもおいしかった。",
    possibleAnswers: [
"溶けて",
"染みて ",
"潤って",
"沈んで",
    ],
    correctAnswerIndex: 1),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 올바른 단어를 선택하세요.\nこのテーブルは私が子どものころから使っているので、(❓)があって捨てられない。",
    possibleAnswers: [
"心情",
"好感 ",
"熱意",
"愛着",
    ],
correctAnswerIndex: 3),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어갈 올바른 단어를 선택하세요.\n現社長は創立者から経営の(❓)を学んだ。",
    possibleAnswers: [
"データベース",
"ベテラン",
"ライフワーク",
"ノウハウ",
    ],
correctAnswerIndex: 3),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어간 단어와 의미가 가장 비슷한것을 보기에서 고르시오.\n以前から-高橋さんには(かねがね)お会いしたいと思っていました",
    possibleAnswers: [
"直接",
"ぜひ",
"早く",
"以前から",
    ],
correctAnswerIndex: 3),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어간 단어와 의미가 가장 비슷한것을 보기에서 고르시오.\n林さんはそれを(故意)に捨てたらしい。",
    possibleAnswers: [
"わざと",
"うっかり",
"いやいや",
"さっさと",
    ],
correctAnswerIndex: 1),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어간 단어와 의미가 가장 비슷한것을 보기에서 고르시오.\n昨日、鈴木さんに(おわびした.)",
    possibleAnswers: [
"文句を言った",
"お礼を言った",
"断った",
"謝った",
    ],
correctAnswerIndex: 3),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어간 단어와 의미가 가장 비슷한것을 보기에서 고르시오.\n中村さんの言葉からは強い(意気込み)が伝わってくる。",
    possibleAnswers: [
"敬意",
"自信",
"意欲",
"信頼",
    ],
correctAnswerIndex: 2),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어간 단어와 의미가 가장 비슷한것을 보기에서 고르시오.\n妹は少し(おびえて)いるようだった.",
    possibleAnswers: [
"焦って",
"怖がって",
"悩んで",
"悔やんで",
    ],
correctAnswerIndex: 1),
    Question(questionText: "다음 일본어 문장을 읽고 괄호 안에 들어간 단어와 의미가 가장 비슷한것을 보기에서 고르시오.\n私はその一言に(安堵)した。",
    possibleAnswers: [
"すっとした ",
"はっとした",
"ほっとした",
"かっとした",
    ],
correctAnswerIndex: 2),
    Question(questionText: "다음 한자를 가장 올바르게 쓴 문장을 보기에서 골라라.\n閑静",
    possibleAnswers: [
"そのレストランは繁華街から外れた閑静な場所にある.",
"今日は朝から具合が悪かったので、会社を休んで家で閑静にしていた。",
"用事が早く済み、閑静な時間ができたので、映画を見に行くことにした。",
"日中はにぎやかな公園だが、夜になると急に閑静になる。",
    ],
correctAnswerIndex: 0),
    Question(questionText: "다음 한자를 가장 올바르게 쓴 문장을 보기에서 골라라.\nたやすい",
    possibleAnswers: [
"弟は寝坊したらしく、たやすい物だけ食べて、慌てて出かけていった。",
"伊藤氏とは大学時代からの親友で、本音が言えるたやすい関係だ。",
"せっかくの日曜日だから、ゆっくり休んでたやすく過ごそうと思う。",
"この問題は想像以上に複雑で、たやすく解決できるものではなかった。",
    ],
correctAnswerIndex: 3),
    Question(questionText: "다음 한자를 가장 올바르게 쓴 문장을 보기에서 골라라.\n察する",
    possibleAnswers: [
"医師たちはチームを組み、意見を出し合って、最良の治療法を察した.",
"気象予報士はテレビの天気予報で、来週の気温の変化を察し始めた。",
"鈴木さんは、私が何も言わなくても、私の気持ちを察して慰めてくれた。",
"外を歩いていたら急にいいアイディアを察したので、手帳にメモをした。",
    ],
correctAnswerIndex: 2),
    Question(questionText: "다음 한자를 가장 올바르게 쓴 문장을 보기에서 골라라.\n内訳",
    possibleAnswers: [
"来週の内訳を確認したが、予定がないのは木曜の夜だけだ。",
"前回の出張費の内訳を見たら、交通費の割合が予想外に高かった。",
"司会者は進行を間違えないように、式の内訳を何度も見直した。",
"家族の健康のため、栄養の内訳を考えて食事を作っている。",
    ],
correctAnswerIndex: 1),
    Question(questionText: "다음 한자를 가장 올바르게 쓴 문장을 보기에서 골라라.\n食い違う",
    possibleAnswers: [
"この事件は、複数の目撃者の話がそれぞれ食い違っており、不明な点が多い。",
"金庫を開けようと思ったが、どの鍵も食い違って開けられなかった。",
"何だか歩きにくいと思ったら、サンダルの左右が食い違っていた。",
"調味料を変えたのか、この料理はいつもと味が食い違っているように感じる。",
    ],
correctAnswerIndex: 0),
   Question(questionText: "다음 한자를 가장 올바르게 쓴 문장을 보기에서 골라라.\n過密",
    possibleAnswers: [
"雑誌で紹介されてから、この商品への過密な注文が続いているらしい。",
"水質汚染に関して人々の抗議が過密になり、政府は対策を迫られている。",
"今回の出張は過密なスケジュールで、ゆっくり食事する時間もなさそうだ。",
"春になると、この池の周りには、色とりどりの花が過密に咲き乱れる。",
    ],
correctAnswerIndex: 2),
    Question(questionText: "다음 한자를 가장 올바르게 쓴 문장을 보기에서 골라라.\n朝の満員電車。車内の混雑を(❓)、私の目の前に座っている学生風の男は、平 然とノートパソコンを広げて、作業に没頭していた。",
     possibleAnswers: [
 "含めて",
 "もとに",
 "除いて",
 "よそに",
     ],
 correctAnswerIndex: 3),
    Question(questionText: "다음 한자를 가장 올바르게 쓴 문장을 보기에서 골라라.\n私の父は、(❓)もしないで漫画を批判するから、本当に嫌になる。",
     possibleAnswers: [
 "読まない",
 "読み",
 "読もう",
 "読んで",
     ],
 correctAnswerIndex: 1),
    Question(questionText: "다음 한자를 가장 올바르게 쓴 문장을 보기에서 골라라.\n村の郷土史をまとめるにあたり、今年90歳になる元村長の東山さんにお話を伺った.\n村に初めて汽車が走ったときのことを鮮明に覚えて(❓)、その記憶力に驚いた。",
     possibleAnswers: [
 "おいでになり",
 "差し上げ",
 "まいり",
 "申し上げ",
     ],
 correctAnswerIndex: 0),
    Question(questionText: "다음 한자를 가장 올바르게 쓴 문장을 보기에서 골라라.\n水道管破裂による断水のため、8月12日まで市民プールの営業を休止します。復旧状況(❓ )、営業再開が遅れる可能性がありますので、ご了承ください。",
     possibleAnswers: [
 "次第には",
 "次第に",
 "次第では",
 "次第",
     ],
 correctAnswerIndex: 2),
    Question(questionText: "教師=話す人、生徒=聞く人という構造が知らず知らずのうちに教室空間にできあがり、そして固定化してしまうのは恐ろしいことではないかと思う。教師が先取りしてしまうことで、生徒が自分自身で考え、解決しようとする芽をつみとってしまう場合がある。いつも話し続けるのがコミュニケーションでない。「待つ」という行為も時には大切であろう。もう少し話したい、と思うところで一歩ひいてみることで、相手が言おうとすることを引き出すことができるのである。\n위 문장을 읽고 필자의 생각에 알맞을것을 네가지 보기중에서 고르세요.",
     possibleAnswers: [
 "教師と生徒が自由に発言し合うことも必要だ。",
 "教師は生徒の考えを想像するべきだ。",
 "教師は生徒の発言を待つことも必要だ。",
 "教師は生徒に沈黙の時間を与えないようにすべきだ。",
     ],
 correctAnswerIndex: 2),
    Question(questionText: "2016年1月1日\nスポーツ課\n市民運動場の予約について\n市民運動場の予約は、これまで管理事務所窓口で受け付けておりましたが、2017 年2月1日よりインターネット上の予約システムでも行うことができるようにな ります。予約システムの利用は平日、土日祝日を問わず24時間可能で、予約は、 窓口での予約と同様に、使用日の一か月前から受け付けます。 予約システムの利用に際しては、事前に利用者登録が必要となりますので、身分 を証明できるものを持って管理事務所窓口にお越しください。\n市民運動場管理事務所 〒02‐383 南松市中央町3‐2 中央公園内\n(受付時間 : 月曜日~金曜日 9:0~17:0)\n위 문장을 읽고 시민운동장의 예약에 대해서 위 문장은 무엇을 알리려고 하는지 네가지 보기중에 고르세요.",
     possibleAnswers: [
 "管理事務所窓口での予約受付期間が変更になること",
 "管理事務所窓口で利用者登録をすれば、インターネット上で予約ができるようになること",
 "インターネット上での予約受付時間がこれまでより長くなること",
 "インターネット上の予約システムの導入により、管理事務所窓口での予約ができなくなること",
     ],
 correctAnswerIndex: 1),
    Question(questionText: "異文化間での対話を議論するときに，必ずといってよいくらい出てくるのが，価値観の理解と共有である。他者と対話を通して，人間関係を樹立していくには，自己の価値観を保存したままで，他者の価値観を理解するという方略だけでは十分ではない。相互的な働きかけを通じて，何か新たな価値を共有することが要求されるのである。すなわち，自らの価値観を相対化し，新たな価値を対話という共同作業を通して創り上げ，それを共有していく態度が必要なのだ。\n筆者によると、異文化間で対話を通して人間関係を築く上で最も大切なことは何か。",
     possibleAnswers: [
 "自己の価値観を理解してもらおうとする態度",
 "自己の価値観を保ちながら、他者の価値観を理解する態度",
 "他者と自己の共通の価値観を創り上げていく態度",
 "他者の価値観の中に自己の価値観との共通点を見つける態度",
     ],
 correctAnswerIndex: 2),
    ]
}
          
   
  

   
